spring:
  application:
    name: product-service
server:
  port: 8081
  forward-headers-strategy: framework

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /product/v3/api-docs
  swagger-ui:
    enabled: false